### PR TITLE
HF22 (HFNET) Consensus Changes

### PR DESCRIPTION
**Pull request by DeckerSU**
**Don't merge** this PR till:
- S6 pubkeys will be 100% collected and corresponding PR with changes in `komodo_globals.h`, `komodo_hardfork.h` will be done.
- S6 NN ops should participate in mandatory `HFNET` testing in which we should test everything with 50% of existing nodes at least, to estimate maximum gap between blocks. Probably `HFNET` should be re-created based on https://github.com/KomodoPlatform repo sources once again.
- As originally this PR was in [KomodoOcean repo](https://github.com/DeckerSU/KomodoOcean/commits/patch-hf22), we should compare all changes once again line-by-line, to be sure that nothing is forgotten and nothing is mixed in logic. Of course, i did all checks by myself twice, but better to have few more pair of eyes open on this.
- When `nS6TestTimestamp` and `nS6TestHardforkHeight` will be set in stone, we should set [`consensus.nHF22Height`](https://github.com/DeckerSU/KomodoOcean/blob/patch-hf22/src/chainparams.cpp#L124), as a week after `nS6TestHardforkHeight` to not overlap two important consensus changes. This should be done **before** merging this PR.
- Patch for `KomodoPlatform/komodo` repo `dev` branch to match current `HFNET` spinned-up by @Alrighttt , i mean [this](https://github.com/Alrighttt/komodo/commits/patch-hf22), available here - [hfnet-alrighttt-changes.zip](https://github.com/KomodoPlatform/komodo/files/8791351/hfnet-alrighttt-changes.zip).
- [Changing p2p port to 8880](https://github.com/KomodoPlatform/komodo/pull/538/commits/2a54247ceec1ce5d8f7d53e0dcb1bf6101ce8bc6) also should be reverted, **before** merging this PR (!), this was done only for `HFNET` and testing purposes.

Currently i selected @ca333 , @Alrighttt and @smk762 for review, but later, after all tests, probably we should give a chance to look on all of these to @jmjatlanta and @dimxy .

### CODE REVIEW

**Comment by TheComputerGenie** [comment]
There seems to be a certain level of counter-productivity in doing this and not removing [the random delay when three are "too few" external miners](https://github.com/KomodoPlatform/komodo/blob/master/src/miner.cpp#L852-L861) as well

**Comment by DeckerSU** [comment]
> There seems to be a certain level of counter-productivity in doing this and not removing [the random delay when there are "too few" external miners](https://github.com/KomodoPlatform/komodo/blob/master/src/miner.cpp#L852-L861) as well

This PR have no any relationship to internal miner behavior. All changes in internal miner that could be possible done in it will be done later, if will.

**Comment by TheComputerGenie** [comment]
> Main goal of this PR is to introduce new consensus rules, which will be able to help overcome "chain stuck" issue and "disappearing transactions" issue, in-case of big gaps between blocks.

Perhaps I used the wrong wording? If you want the chain to stick less and want NNs to assist in said goal then one important step in doing so would be removing a code block that intentionally delays them from sending blocks during the time you want them to be creating more blocks.

The flaw in the notion that "no significant relationship to internal miner behavior" can solve a problem that the "internal miner behavior" is coded to create is that **it's coded to fight against the goal of the PR**.

On one hand you're allowing NNs to mine more often, on the other hand you're keeping in code that, in most circumstances, _disallows them from creating a block in the time frame you want them to create it in._

**Comment by DeckerSU** [comment]
> Perhaps I used the wrong wording? If you want the chain to stick less and want NNs to assist in said goal then one important step in doing so would be removing a code block that intentionally delays them from sending blocks during the time you want them to be creating more blocks.

Forget about internal miner implementation on a second. Let's imagine that part of NNs using it, and other part using other solution for creating blocks, you could imagine that NNs could create a block at the click of a finger :magic_wand:, for example. In case of absent of "external" PoW miners (`gpucount == 0`) - removing the delay you pointed earlier will not help anyhow, in case of chain stuck. Bcz last 64 blocks was created by NNs, and we will face with a "no one allowed to mine a block" case. One of the intents of this PR is to rule out such cases.

**Comment by TheComputerGenie** [comment]
> p.s. Try to abstract of internal miner usage for now, i mean when thinking of "how it will be".

I would and I could, except for the fact that my mind is incapable of seeing a thing fight against itself.
Ignoring one part of the code while implementing a competing code tells the running node:
> The network needs you to create an extra block now because the chain isn't moving due to lack of hashrate and we need blocks now! Oh, and also, you possibly can't submit it for another 14 minutes, even though you're allowed to create it now and we need it now because there haven't been enough hashrate blocks created.

I sometimes think that people reject reading my words just because they come from me.

**Comment by DeckerSU** [comment]
> Both things should be done at the same time and with multiple testers. Ignoring one part of the code while implementing a competing code tells the running node:

It's not "ignoring". As i said above: "And yes, we will return to timeframes, delays, and other "artificial things" in internal miner later, i.e. in other PRs". At this stage let's separate internal miner things and consensus things. Within this PR we are talking only about consensus changes.

**Comment by DeckerSU** [comment]
PR is [updated](https://github.com/KomodoPlatform/komodo/pull/538#issuecomment-1140334292). Time to review and merge together with #538.

**Review by Alrighttt — APPROVED** [review]
Consensus changes tested thoroughly via HFNET. 

Thanks for the notaryvin clean up as well.

**Review by ca333 — APPROVED** [review]

**Pull request merged**
