### PR TITLE
allow -ac_private for the ZOMBIE test chain

### PR DESCRIPTION
**Pull request by DeckerSU**
Better solution for the issues mentioned in https://github.com/KomodoPlatform/komodo/pull/589 .

### CODE REVIEW

**Comment by TheComputerGenie** [comment]
Wouldn't the "better solution" be to drop the concept? We don't seem to support the opposite concept (coding "if you want public only, you cannot have it because there's no reason to just not use KMD").

**Comment by DeckerSU** [comment]
> Wouldn't the "better solution" be to drop the concept? We don't seem to support the opposite concept (coding "if you want public only, you cannot have it because there's no reason to just not use KMD").

If you would like to discuss the "concept" itself, please create a separate issue. Your comment is not related to this pull request, which is solely intended to add permission for the `ZOMBIE` chain to use `-ac_private`. If you believe this permission should be extended to other chains as well, please explain why in a separate issue. Thank you!

**Review by smk762 — APPROVED** [review]
Thanks!
Confirmed no issues with launch for KMD, PIRATE or ZOMBIE, and shutdown when attempting launch of private chain with tickers not in the allow list.

**Comment by TheComputerGenie** [comment]
> > Wouldn't the "better solution" be to drop the concept? We don't seem to support the opposite concept (coding "if you want public only, you cannot have it because there's no reason to just not use KMD").
> 
> If you would like to discuss the "concept" itself, please create a separate issue. Your comment is not related to this pull request, which is solely intended to add permission for the `ZOMBIE` chain to use `-ac_private`. If you believe this permission should be extended to other chains as well, please explain why in a separate issue. Thank you!

Yes, I'll get right on creating a separate issue which addresses this pull request which addresses an issue that isn't this pull request so that that not-new issue (which addresses this pull request which addresses an issue that isn't this pull request) can sit ignored for years and then quietly closed; that's a much better solution than discussing the merits of this pull request inside the conversation mechanism of this pull request.

**Review by dimxy — APPROVED** [review]
LGTM
I was able to run ZOMBIE node with this fix,
this also fixes an issue when ac_name was an unsupported private chain we got a misleading 'error in HDD data' msg

**Pull request merged**
