### PR TITLE
Lock cs_main for TestBlockValidity

### PR DESCRIPTION
**Pull request by jmjatlanta**
Fixes issue #483 

The BitcoinMiner() did not properly lock cs_main before using chainActive or calling TestBlockValidity. 

I have verified that all other calls to TestBlockValidity maintain the lock on cs_main before the call.

### CODE REVIEW

**Review by dimxy — DISMISSED** [review]
I agree with this fix.
Actually I have already added this lock in my experimental branches. I did load tests with and without it and got -25 mempool errors when the lock omitted

**Comment by DeckerSU** [comment]
Actually `CChain::LastTip()` is kind of a hack introduced in our codebase few years ago (in 2018), all Bitcoin-based coins using `CChain::Tip()` to get the index entry for the last tip of chain. So, my offer is to follow the Bitcoin codebase:

- get rid of this `CChain::LastTip()` and change all `LastTip()` calls on `Tip()`.
- don't try to introduce new methods, like `GetLastTipWithLock()`, but just use `LOCK(cs_main)` instead where needed.

It will be more clear and make the codebase following bitcoin upstream at the same time. Actually we have a lot of things which are implemented in Bitcoin, but absent in Komodo ... if you'll look on ZCash codebase - they trying to merge Bitcoin upstream step-by-step ... my opinion - we should do the same first: try to take the best from Bitcoin upstream and minimize introducing "in-place" fixes like `GetLastTipWithLock()`.

**p.s.** All of above is just my personal opinion.

**Comment by dimxy** [comment]
maybe let's now replace LastTip everywhere (it is really confusing)
not use GetLastTipWithLock and run more tests with DEBUGLOCKORDER on later
but add now LOCK(cs_main) for TestBlockValidity: I believe running it without a lock is dangerous for critical code

**Review by dimxy — DISMISSED** [review]
maybe this function GetLastTipWithLock() is not needed as we agreed not to use it

**Comment by jmjatlanta** [comment]
Conflict resolved.

**Comment by dimxy** [comment]
I am running my NN on this code, seems this okay.
I have code in succession for this PR with more refactoring of mining code: use LOCK2 in CreateNewBlock, block connecting code moved out from validBlock(), elimination of extra call to TestLockValidity - still in testing.
But for now this PR#486 code could be used on dev NNs to fix the deadlock situation (https://github.com/KomodoPlatform/komodo/issues/554)

**Review by Alrighttt — APPROVED** [review]

**Comment by Alrighttt** [comment]
LGTM, but I did not personally test as I no longer have access to a notary.

**Review by DeckerSU — APPROVED** [review]
LGTM generallу.

**p.s.** May be we also need to include this changes https://github.com/zcash/zcash/pull/5853 in this PR. Good to have protection if chain tip is nullptr somehow. I [added](https://github.com/DeckerSU/KomodoOcean/commit/f6ce184b2c5561a7ab9e5514887b11d3e412e998) this change to Komodo-Qt codebase.

**Comment by dimxy** [comment]
> **p.s.** May be we also need to include this changes [zcash#5853](https://github.com/zcash/zcash/pull/5853) in this PR. Good to have protection if chain tip is nullptr somehow. 

Currently this code https://github.com/KomodoPlatform/komodo/blob/d456be35acd1f8584e1e4f971aea27bd0644d5c5/src/init.cpp#L2016 in AppInit2() ensures that the genesis block is imported (and chainActive becomes not empty) before mining starts
But there is a bad thing that if fShutdown is set chainActive still may be empty. So I think first we should add a return false if fShutdown is true. And we could also add zcash#5853 for better safety

**Comment by dimxy** [comment]
> p.p.s. Also github web ui shows that this PR changes marmara.cpp which is absent at the moment. As I remember we get rid of it earlier, or I did it only in Komodo-Qt codebase.

I remember jmjatlanta intended to remove marmara.cpp but now I have all his PRs merged in my branch and marmara.cpp is still here. Maybe he did not make a PR with this removal

**Comment by tonymorony** [comment]
these changes implemented in combined PR: https://github.com/KomodoPlatform/komodo/pull/559

**Pull request closed without merging**
