### PR TITLE
Refactor configuration file reading

### PR DESCRIPTION
**Pull request by jmjatlanta**
There are several ways that configuration files are found and read. This PR aims to consolidate them into one place.

The basics are:
- A new komodo_config.c/h that holds the logic for finding, reading and writing config files.
- Removal of such logic from komodo_utils.h
- Removal of globals within the reading/writing of configuration files, pushing them further up the software stack

No functionality should have been changed.

### CODE REVIEW

**Comment by jmjatlanta** [comment]
There are a couple of logic changes in the komodo_configfile method that I __think__ are bugfixes, but am unsure.
1. komodo_configfile was only called if the desired config file was not found. So the 1 call to this method created the file. But if the file was there (which I believe never happened), the mapArgs of `rpcusername` and `rpcpassword` were set. That does not make sense to me because why wouldn't you set them if you created the file. I __think__ those mapArgs should always be set when calling those methods.
2. The mapArgs of `rpcusername` is never used. There is a mapArgs of `rpcuser`, so I __think__ that's what should be set.

Also during the call to komodo_configfile, the old logic read `komodo.conf` after reading the chain-specific config file. I consider this a hidden consequence, so moved that logic to within the caller's code.

**Comment by DeckerSU** [comment]
I guess we don't need such routines, like in `parse_conf_line`, `komodo_rpc_info`, etc. at all. I mean, all we need to parse config file and extract `rpcuser`, `rpcpassword`, `ipaddress` variables from it -  we already have in:
```
void ReadConfigFile(map<string, string>& mapSettingsRet,
                    map<string, vector<string> >& mapMultiSettingsRet)
```
Just need bit modify it to use passed file name or coin symbol (depends on the places from which it's called), instead of `GetConfigFile` and then we could extract everything needed in just 3 lines of code, like:
```
std::map<string, string> tmpMapSettingsRet; std::map<string, vector<string> > tmpMapMultiSettingsRet;
ReadConfigFile(GetSymbolConfigFile(ASSETCHAINS_SYMBOL), tmpMapSettingsRet, tmpMapMultiSettingsRet);
if (tmpMapSettingsRet.count("rpcuser") results.username = tmpMapSettingsRet["rpcuser"];
...
```
It's just an example how it could be implemented. You have to admit that using `ReadConfigFile` for parse `.conf` is much more better than using legacy C code with things like `parse_conf_line`. Also, let's look on the [rpc_info](https://github.com/KomodoPlatform/komodo/pull/471/files#diff-d3c1905b040bde2657c97ad602ddfd7dd82febd72aad87a9c6ebfe425c737c55R24) struct. I guess we really don't want to leave it as is with `[512]` char fields. Bcz [here](https://github.com/KomodoPlatform/komodo/pull/471/files#diff-8c615b8141d5c4571d6e6f6df973dc589d2da5a545180eb4f0f3d1abfe813b0aR53) we are just using `strcpy` to fill that struct. What will happen if username or password will be greater than 512?

May be you planned these changes for the "next stage" of refactoring, but my own main rule for all improvements:
- Make it better as much as possible, or don't touch it at all.

For these sources i would like to get rid of all legacy C code, C-style working with null-terminated strings and use existing C++ code everywhere wherever it's possible.

**Comment by DeckerSU** [comment]
May be here we should use standart [ReadConfigFile](https://github.com/KomodoPlatform/komodo/blob/db5b016cf7b8ffffe440ad774dee8c6815ce5726/src/util.cpp#L714) routine from `src/util.cpp` instead of old C-stuff like `parse_conf_line` or new `ConfigFile` class, bcz:
- it's C++ like style and using `boost::program_options::detail::config_file`
- it have built-in negative settings logic
- it fills map and multimap with keys and values `mapSettingsRet`, `mapMultiSettingsRet` and such behavior are very familiar to all devs dealing with Bitcoin sources.

And for writing config file may be more logic (as opposite to `ReadConfigFile`) will be to have `WriteConfigFile` which will fill `key=value` text file from `mapSettingsIn` (map), `mapMultiSettingsIn` (multimap) vars?

Consider this just as an proposal.

**Comment by jmjatlanta** [comment]
> May be here we should use standard [ReadConfigFile](https://github.com/KomodoPlatform/komodo/blob/db5b016cf7b8ffffe440ad774dee8c6815ce5726/src/util.cpp#L714) routine from `src/util.cpp`

Your points have merit. Thank you for the input. I now see that improvements to ConfigFile (or outright replacement) are necessary. But there are a few kinks that I'd love to tackle, and I'm hoping to make baby steps to get there...

1. Merging the config file with the command line parameters - Can we guarantee that command line parameters will ALWAYS override confg file entries? If so, it may be useful to handle that while reading the config file. If not, in my opinion the responsibility does not belong in ReadConfigFile.
2. Must we use a map AND a multimap? Why not hide that complexity behind some kind of interface (part of the intent of why ConfigFile was created)?
   - configFile.Value(key) and configFile.Values(key) seem intuitive to me. Perhaps a configFile.Count(key) would be useful?
3. Processing the init stuff in Komodo is WAY too complicated for (my opinion) no reason other than the codebase grew over time.
   - Having ReadConfigFile set BITCOIND_RPCPORT now looks ridiculous, and dangerous. 
   - Having AppInit(), AppInit2(), chainparams_commandline() etc. contain 1000's of lines in large functions, mapArgs all over the place, changing mapArgs values outside of these initialization routines etc. All of this is symptomatic of not having a plan up front, or ignoring the plan when a deadline approaches.

My longer-term solution (open to debate and changes) is to modularize. We still need to handle things like the need to read both MYCOIN.conf and Komodo.conf. But why not set these structures up within smaller, manageable, and context-specific routines? Yes, that means more init functions not less, but wouldn't you rather look through 25 (or even 50) lines of the constructor called in these 3 lines of code... 
```
AssetChain assetChain(configCollection, assetChainSymbol);
AssetChain komodoChain(configCollection, komodoSymbol);
AssetChain notaryChain(configCollection, notarySymbol);
```
to see what gets put in assetChain.rpc.port instead of slogging through more than 1000 (!?!) lines of AppInit2 to find out how BITCOIND_RPCPORT gets set  (Or is that ASSETCHAIN_RPCPORT that I need, or is it DEST_PORT, or maybe KMD_PORT)?  Hint: BITCOIN_RPCPORT is not set there. It is set in util.cpp.ReadConfigFile, as well as komodo_utils.h.komodo_args (in 2 places), and in bitcoin-cli.cpp and komodo_globals.h.

Ok, I'll stop now. Wow, I feel better. Thank you for listening. Have you ever thought of getting into psychiatry? :-)

**Comment by jmjatlanta** [comment]
Okay, maybe I wasn't done. :-)

>     * it's C++ like style and using `boost::program_options::detail::config_file`

boost::program_options is great once you learn how to use it. With a bit of planning, it can also take care of help messages and such. If we want to use it to its full potential, it would take a buy-in from everyone, but it gives us some cool stuff for the effort (i.e. -v == /v == --verbose, negative syntax, etc.).

>    such behavior are very familiar to all devs dealing with Bitcoin sources.

CPPDevs.size() > CPP_BTC_Devs.size(). Just sayn'

**Comment by DeckerSU** [comment]
> CPPDevs.size() > CPP_BTC_Devs.size(). Just sayn'

Of course, i'm agree ) I just tried to express my point of view.
> Must we use a map AND a multimap? Why not hide that complexity behind some kind of interface (part of the intent of why ConfigFile was created)?

It's not mandatory, but if existing system built on map and multimap entites and if finally all parameters - read from config file or passed from command line are parsed and stored in those map and multimap, why we need other entity to parse and store such things? I like your `ConfigFile` implementation and it looks great, i just want to "unify" interfaces and storage places. Mean, if we will decide that we will use `ConfigFile` class as a thing to parse and store params - we should get rid of `mapArgs`, `mapMultiArgs` and all stuff like `GetArg`, `SoftSetArg`, etc. If we will continue to use `mapArgs`, `mapMultiArgs` based storage for params, expediency of use `ConfigClass` for store params - is a question. 

Also, i'm personally don't like new entites for such things, bcz Komodo is a fork of ZCash, and ZCash is a fork of Bitcoin and in case if we need to copy & paste / cherry-pick some new features / fixes from Bitcoin codebase it will be better if our own codebase will be closer to Bitcoin as much as possible. Mean, if Bitcoin uses `mapArgs`, `mapMultiArgs` (or `ArgsManager` class to handle args in newer versions) - it will be good (from that point of view) if we will use such approach too. It will make "code transfer" / compatability between KMD and BTC codebases easier. Isn't it?

**p.s.** Btw, will we leave `komodo_rpc_info` and `struct rpc_info` in our sources as is? I mean that struct:
```
struct rpc_info
{
    char username[512];
    char password[512];
    char ipaddress[100];
    uint32_t port;
};
```
Have limited space for store `username` and `password` fields, and [komodo_rpc_info](https://github.com/KomodoPlatform/komodo/pull/471/files#diff-8c615b8141d5c4571d6e6f6df973dc589d2da5a545180eb4f0f3d1abfe813b0aR26) we just use `strcpy` to fill these fields:
```
strcpy(results->username, parse_conf_line(str, "rpcuser"))
```
I know that is very rare / almost impossible case, but what if somebody will set 513 chars password or username in `.conf`? Isn't better to use `std::string` in `rpc_info` struct?

**Comment by jmjatlanta** [comment]
I agree @DeckerSU on your points. It is very useful to hear it from someone more familiar with the history of the codebase.

The std::string vs char[512] is a good question. This is a case of me replacing some c code with something kinda-like some c++ code so I don't need to make .c functions call a c++ library. I should take the extra time to get everything using the same system. At the point of doing what I did, I didn't know if even those .c files were still used.

The point about keeping the codebases similar is a difficult one. It is always great to be able to merge in the work of others and get new features, but there is a cost involved. How much we want to make codebases match versus deviate are questions I should not answer (too new). But that answer has a very large impact on whether I'm going in the right direction or not. I look to yourself and others for guidance on this point.

**Comment by jmjatlanta** [comment]
Question for all: 

Background: I am modifying komodo_rpc_info to help c routines access config files by calling the same c++ methods others use. The two applications that use this are rogue and dapps. 

Question: How do I compile these components? The normal build process does not seem to reference these. Running src/cc/Makefile_rogue gives compile errors that make me think these things aren't even used. But it could be (highly likely) I simply am not following the proper build procedure.

Pointing me to documentation would be great. Meanwhile, I'll keep digging.

What I'm seeing:
```
make -f Makefile_rogue

Linux
Building cclib to src/
LINUX
gcc -Wno-write-strings -DBUILD_ROGUE -std=c++11 -I../../depends/x86_64-unknown-linux-gnu/include -I../univalue/include -I../cryptoconditions/include -I../cryptoconditions/src -I../cryptoconditions/src/asn -I.. -I. -fPIC -shared -O0 -D _DEBUG -o librogue.so -c cclib.cpp
In file included from cclib.cpp:656:
rogue_rpc.cpp: In function ‘UniValue rogue_games(uint64_t, CCcontract_info*, cJSON*)’:
rogue_rpc.cpp:1466:20: error: ‘const class uint256’ has no member named ‘first’
 1466 |         txid = it->first.txhash;
      |                    ^~~~~
rogue_rpc.cpp:1467:29: error: ‘const class uint256’ has no member named ‘first’
 1467 |         vout = (int32_t)it->first.index;
      |                             ^~~~~
In file included from cclib.cpp:670:
rogue/rogue.c: In function ‘int32_t rogue_progress(rogue_state*, int32_t, uint64_t, char*, int32_t)’:
rogue/rogue.c:163:1: warning: no return statement in function returning non-void [-Wreturn-type]
  163 | }
      | ^
make: *** [Makefile_rogue:24: librogue.so] Error 1
```

**Comment by jmjatlanta** [comment]
Closing this in favor of following the more recent Bitcoin model of configuration handling. There is little sense in working on this now only to replace it in the near future.

**Pull request closed without merging**
