### PR TITLE
Pytest sync, update workflows

### PR DESCRIPTION
**Pull request by SirSevenG**
Sync pytests with research branch
Minor tests fixes to correctly work with dev branch
Switch to 30s blocktime bootstrap for pytests
Update version of GH actions from deprecated ones (v1 -> v3) https://github.com/actions/checkout https://github.com/actions/upload-artifact https://github.com/actions/download-artifact

Fix windows CI build

@dimxy @DeckerSU There are issues with macOS build, I don't have Intel mac to recheck locally and it's problematic to debug the build in Actions - macOS eats Actions usage time too fast. Please take a look when you can.

~~Draft for now, need to fix macOS first.~~ Still an improvement over current state. )

Also should close: https://github.com/KomodoPlatform/komodo/issues/560

### CODE REVIEW

**Comment by dimxy** [comment]
> There are issues with macOS build, I don't have Intel mac to recheck locally and it's problematic to debug the build in Actions - macOS eats Actions usage time too fast. Please take a look when you can.

I regularly build on intel mac without any issues and I have never seen errors like in this github mac build.

**Comment by smk762** [comment]
I've merged this into https://github.com/KomodoPlatform/komodo/pull/575 for working on fixing the mac builds. So far got it working on macos-11, but not yet on macos-12 / macos-latest runners

**Comment by DeckerSU** [comment]
> I regularly build on intel mac without any issues and I have never seen errors like in this github mac build.

macOS 12 (Monterrey) and latest XCode `14.2` (Build version `14C18`) introduces many issues into our build. For example,  Rust 1.32 produced a slightly invalid format `.rlib`s that newer versions of xcode are more restrictive on. So, there is a two possible solutions: downgrade XCode to `13.2.1` or upgrade Rust to `1.54` or newer. Also, seems `gcc@8` produce an incorrect binaries on macOS 12 somehow ... I just have finished fixing the issues with native Mac x86_64 build for KomodoOcean ... and now will focus on `komodod`.

**Comment by TheComputerGenie** [comment]
Given that gcc 8 series is so old that it hasn't been supported by GNU for nearly 2 years, it would seem that the "proper" path forward would be to update any code which no longer meets industry standards.

**Pull request merged**
