### PR TITLE
Use gcc-9 for macOS builds

### PR DESCRIPTION
**Pull request by smk762**
Closes https://github.com/KomodoPlatform/komodo/issues/616

### CODE REVIEW

**Review by dimxy — APPROVED** [review]
LGTM

**Comment by DeckerSU** [comment]
LGTM also, but I need to conduct some tests on Mac, such as a full-sync, and other internal tests before I can give explicit approval. Therefore, it will be labeled as "Under Testing" until I complete all the necessary checks. I strongly believe that we should stop using `gcc` on Mac and switch to the native `clang`, as I have already done in the `KomodoOcean` repository. This is on my to-do list and I plan to open a separate PR for this till the next season. For now, we will continue with `gcc@9`.

**p.s.** Also we need to update instructions in README: 

https://github.com/KomodoPlatform/komodo/blob/261233ccaeea4514b04c03f422ccfb56db1fb977/README.md?plain=1#L97

**Comment by DeckerSU** [comment]
The compiler changes for Mac mentioned earlier are now available here: https://github.com/KomodoPlatform/komodo/pull/618

**Comment by TheComputerGenie** [comment]
If the object is to update, why not update to a version that's modern enough to be supported in the future rather than the oldest working but most likely to be disabled version?
8 is no longer supported so move to 9 rather than 10, 11, 12, or 13?
I asked this in another post, but: Is there some logical reason that we observers are missing that justifies not making things for the future rather than so old that no one supports them? [or in this case will soon no longer support them]

**Comment by smk762** [comment]
> If the object is to update, why not update to a version that's modern enough to be supported in the future rather than the oldest working but most likely to be disabled version? 8 is no longer supported so move to 9 rather than 10, 11, 12, or 13? I asked this in another post, but: Is there some logical reason that we observers are missing that justifies not making things for the future rather than so old that no one supports them? [or in this case will soon no longer support them]

In some cases, its for backwards compatibility so people using older operating systems which are still supported (i.e. not yet at EOL) can continue use the app/binary etc. Another consideration is resulting required code / syntax changes which the dependency being updated has breaking changes, or triggers a cascade of other deps needing updates or deps being incompatible if one doesnt support the other yet. Resource allocation is also a consideration. If I can change a number in a few files and it works, I dont need to spend hours/days on a while bunch of other changes trying to make it work.

**Pull request closed without merging**
