### PR TITLE
adds fetch-params script that still uses zcash url

### PR DESCRIPTION
**Pull request by gcharang**

### CODE REVIEW

**Comment by DeckerSU** [comment]
About #458 we should agreed - will we use self-hosted as it already merged in #450 or continue to use ZCash.

If self-hosted - this PR should be closed. If continue to use ZCash - #450 should be reverted, and #458 should add needed changes in `fetch-params.bat` also.

**Comment by gcharang** [comment]
Our self hosted version is on a VPS right now and may not be able to serve many concurrent downloads. Adding this script till we setup a CDN for these files

**Comment by DeckerSU** [comment]
> Our self hosted version is on a VPS right now and may not be able to serve many concurrent downloads. Adding this script till we setup a CDN for these files

Then we need changes in `fetch-params.bat` also:

**fetch-params.bat.patch**
```
diff --git a/zcutil/fetch-params.bat b/zcutil/fetch-params.bat
index f9e70d481..0b542d28c 100644
--- a/zcutil/fetch-params.bat
+++ b/zcutil/fetch-params.bat
@@ -6,7 +6,7 @@ MKDIR "%APPDATA%"\ZcashParams
 )
 IF NOT EXIST "%APPDATA%"\ZcashParams\sprout-proving.key (
     ECHO Downloading Zcash trusted setup sprout-proving.key, this may take a while ...
-    .\wget64.exe --progress=dot:giga --continue --retry-connrefused --waitretry=3 --timeout=30 https://z.cash/downloads/sprout-proving.key -O "%APPDATA%"\ZcashParams\sprout-proving.key
+    .\wget64.exe --progress=dot:giga --continue --retry-connrefused --waitretry=3 --timeout=30 https://z.cash/downloads/sprout-proving.key.deprecated-sworn-elves -O "%APPDATA%"\ZcashParams\sprout-proving.key
 )
 IF NOT EXIST "%APPDATA%"\ZcashParams\sprout-verifying.key (
     ECHO Downloading Zcash trusted setup sprout-verifying.key, this may take a while ...
```

**Comment by gcharang** [comment]
> add the changes above in this PR as well

done

**Comment by gcharang** [comment]
@DeckerSU are the patches you shared enough or should I change the rest of the `komodoplatform.com` strings to `z.cash` strings in  both the `./zcutil/VerusCoin.xml` and `./zcutil/fetch-params.bat` files?

**Comment by DeckerSU** [comment]
> @DeckerSU are the patches you shared enough or should I also change the rest of the `komodoplatform.com` strings to `z.cash` strings in both the `./zcutil/VerusCoin.xml` and `./zcutil/fetch-params.bat` files?

Depends on what we will do with #457 and #450 , wait for #457 merged and depends on will #450 in #457 will be reverted or not -> update #458.

**Comment by gcharang** [comment]
@DeckerSU @ca333 please review

I removed the `fetch-params-zcash.sh` filed and updated the contents of `fetch-params.sh` to use the `https://z.cash/downloads/sprout-proving.key.deprecated-sworn-elves` file

for now all the fetch scripts(including windows ones) use the https://z.cash/downloads/sprout-proving.key.deprecated-sworn-elves file and the usual z.cash urls for the rest

only the `fetch-params-alt.sh` script uses the selfhosted versions 

we can switch all the scripts to self hosted once we have CDN ready for these files

**Comment by ca333** [comment]
> @DeckerSU @ca333 please review
> 
> I removed the `fetch-params-zcash.sh` file and updated the contents of `fetch-params.sh` to use the `https://z.cash/downloads/sprout-proving.key.deprecated-sworn-elves` file
> 
> for now all the fetch scripts(including windows ones) use the https://z.cash/downloads/sprout-proving.key.deprecated-sworn-elves file and the usual z.cash urls for the rest
> 
> only the `fetch-params-alt.sh` script uses the selfhosted versions
> 
> we can switch all the scripts to self hosted once we have CDN ready for these files

sounds good. maybe we should add the corresponding `fetch-params-alt.bat` ?

Discussing further enhancements - e.g. sprout should not be used anymore, really - thus sprout params requirement removal will come sooner than later.

**Comment by gcharang** [comment]
@ca333 pushed alt script for win

**Comment by ca333** [comment]
> @ca333 pushed alt script for win

thanks - were all scripts tested and was the 404 ref. zcash src just temporary?

**Comment by gcharang** [comment]
when there was 404s,
it was because https://z.cash/downloads/sprout-proving.key didn't exist and was moved to https://z.cash/downloads/sprout-proving.key.deprecated-sworn-elves

so, based on https://github.com/KomodoPlatform/komodo/pull/450#issuecomment-851603223
all the scripts ex: fetch-params.sh , fetch-params.bat , VerusCoin.xml are changed

I tested the fetch-params.sh being submitted in this PR and it works
so the win versions should work as well

**Review by ca333 — APPROVED** [review]

**Pull request merged**
