### PR TITLE
 rm template matching and pseudo opcodes

### PR DESCRIPTION
**Pull request by ca333**
cc: @jl777 @DeckerSU

### CODE REVIEW

**Comment by DeckerSU** [comment]
`./komodo-test` have Segmentation fault, when running `testInvalidNotarisationBadOpReturn` test:

```
[ RUN      ] TestEvalNotarisation.testInvalidNotarisationBadOpReturn

Program received signal SIGSEGV, Segmentation fault.
0x00005555557c6cf5 in CheckTxAuthority (tx=..., auth=...) at crosschain_authority.cpp:33
33              if (!eval->GetTxUnconfirmed(txIn.prevout.hash, tx, hashBlock)) return false;
(gdb) bt
#0  0x00005555557c6cf5 in CheckTxAuthority (tx=..., auth=...) at crosschain_authority.cpp:33
#1  0x000055555566a9e0 in Eval::CheckNotaryInputs (this=<optimized out>, tx=..., height=<optimized out>, timestamp=<optimized out>) at cc/eval.cpp:179
#2  0x000055555566d317 in Eval::GetNotarisationData (this=this@entry=0x7fffffffcde0, notaryHash=..., data=...) at cc/eval.cpp:190
#3  0x000055555562338d in TestEvalNotarisation::TestEvalNotarisation_testInvalidNotarisationBadOpReturn_Test::TestBody (this=<optimized out>)
    at test-komodo/test_eval_notarisation.cpp:147
#4  0x0000555555669ecf in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
    at /home/decker/ssd_nvme/komodo_malpill/depends/x86_64-unknown-linux-gnu/share/../include/boost/system/detail/std_interoperability.hpp:142
#5  0x0000555555660d20 in testing::Test::Run() ()
    at /home/decker/ssd_nvme/komodo_malpill/depends/x86_64-unknown-linux-gnu/share/../include/boost/system/detail/std_interoperability.hpp:142
#6  0x0000555555660ded in testing::TestInfo::Run() ()
    at /home/decker/ssd_nvme/komodo_malpill/depends/x86_64-unknown-linux-gnu/share/../include/boost/system/detail/std_interoperability.hpp:142
#7  0x0000555555660eeb in testing::TestCase::Run() ()
    at /home/decker/ssd_nvme/komodo_malpill/depends/x86_64-unknown-linux-gnu/share/../include/boost/system/detail/std_interoperability.hpp:142
#8  0x000055555566117a in testing::internal::UnitTestImpl::RunAllTests() ()
    at /home/decker/ssd_nvme/komodo_malpill/depends/x86_64-unknown-linux-gnu/share/../include/boost/system/detail/std_interoperability.hpp:142
#9  0x000055555566a387 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::
internal::UnitTestImpl::*)(), char const*) ()
    at /home/decker/ssd_nvme/komodo_malpill/depends/x86_64-unknown-linux-gnu/share/../include/boost/system/detail/std_interoperability.hpp:142
#10 0x000055555566146c in testing::UnitTest::Run() ()
    at /home/decker/ssd_nvme/komodo_malpill/depends/x86_64-unknown-linux-gnu/share/../include/boost/system/detail/std_interoperability.hpp:142
#11 0x00005555555eec98 in RUN_ALL_TESTS () at /home/decker/ssd_nvme/komodo_malpill/depends/x86_64-unknown-linux-gnu/share/../include/gtest/gtest.h:2233
#12 main (argc=1, argv=0x7fffffffda38) at test-komodo/main.cpp:21
```

**Comment by tonymorony** [comment]
Btw in case if we starting to work on C code unit-tests base enlarging we can add `./komodo-test` tests to Github Action CI/CD.
Please let me know if it neeed @ca333 @DeckerSU

**Comment by DeckerSU** [comment]
Btw ... segfault seems happens here:

https://github.com/KomodoPlatform/komodo/blob/a570d7a69a7af135996f160ee519e696964c0e3c/src/test-komodo/test_eval_notarisation.cpp#L44
            bool GetTxUnconfirmed(const uint256 &hash, CTransaction &txOut, uint256 &hashBlock) 

When we modify `hashBlock`, right after return it crashes. If we will comment this line and leave `hashBlock` untouched here, there is no segfault. But coinimport tests will fail:
```
[  FAILED  ] 8 tests, listed below:
[  FAILED  ] TestCoinImport.testProcessImportThroughPipeline                                                 
[  FAILED  ] TestCoinImport.testImportTombstone
[  FAILED  ] TestCoinImport.testWrongChainId
[  FAILED  ] TestCoinImport.testPayoutTooHigh
[  FAILED  ] TestCoinImport.testAmountInOpret
[  FAILED  ] TestCoinImport.testInvalidPayouts
[  FAILED  ] TestCoinImport.testCouldntLoadMomom
[  FAILED  ] TestCoinImport.testMomomCheckFail
```

**Comment by ca333** [comment]
> `./komodo-test` have Segmentation fault, when running `testInvalidNotarisationBadOpReturn` 

thanks for hinting @DeckerSU - this one was already known and is not related to the updates from #298 - i can work on a fix at a later stage. But would be glad if you find time earlier though.

**Comment by ca333** [comment]
> Btw in case if we starting to work on C code unit-tests base enlarging we can add `./komodo-test` tests to Github Action CI/CD.
> Please let me know if it neeed @ca333 @DeckerSU

Thanks @tonymorony - yes, lets add that when we fixed `komodo-test`

**Comment by DeckerSU** [comment]
@ca333 finally, seems i found a root of segfault in `komodo-test` and **fixed** it. Apply this patch:
```
diff --git a/src/test-komodo/test_eval_notarisation.cpp b/src/test-komodo/test_eval_notarisation.cpp
index f0c48f951..2256f4761 100644
--- a/src/test-komodo/test_eval_notarisation.cpp
+++ b/src/test-komodo/test_eval_notarisation.cpp
@@ -130,6 +130,7 @@ TEST(TestEvalNotarisation, testInvalidNotaryPubkey)
 TEST(TestEvalNotarisation, testInvalidNotarisationBadOpReturn)
 {
     EvalMock eval;
+    EVAL_TEST = &eval;
     CMutableTransaction notary(notaryTx);
 
     notary.vout[1].scriptPubKey = CScript() << OP_RETURN << 0;
@@ -143,6 +144,7 @@ TEST(TestEvalNotarisation, testInvalidNotarisationBadOpReturn)
 TEST(TestEvalNotarisation, testInvalidNotarisationTxNotEnoughSigs)
 {
     EvalMock eval;
+    EVAL_TEST = &eval;
     CMutableTransaction notary(notaryTx);
 
     SetupEval(eval, notary, [](CMutableTransaction &tx) {
@@ -157,6 +159,7 @@ TEST(TestEvalNotarisation, testInvalidNotarisationTxNotEnoughSigs)
 TEST(TestEvalNotarisation, testInvalidNotarisationTxDoesntExist)
 {
     EvalMock eval;
+    EVAL_TEST = &eval;
     CMutableTransaction notary(notaryTx);
 
     SetupEval(eval, notary, noop);
@@ -169,6 +172,7 @@ TEST(TestEvalNotarisation, testInvalidNotarisationTxDoesntExist)
 TEST(TestEvalNotarisation, testInvalidNotarisationDupeNotary)
 {
     EvalMock eval;
+    EVAL_TEST = &eval;
     CMutableTransaction notary(notaryTx);
 
     SetupEval(eval, notary, [](CMutableTransaction &tx) {
@@ -183,6 +187,7 @@ TEST(TestEvalNotarisation, testInvalidNotarisationDupeNotary)
 TEST(TestEvalNotarisation, testInvalidNotarisationInputNotCheckSig)
 {
     EvalMock eval;
+    EVAL_TEST = &eval;
     CMutableTransaction notary(notaryTx);
 
     SetupEval(eval, notary, [&](CMutableTransaction &tx) {
```
as
```git apply -v segfault.patch```

**Comment by ca333** [comment]
> @ca333 finally, seems i found a root of segfault in `komodo-test` and **fixed** it.

excellent - thanks @DeckerSU

**Comment by DeckerSU** [comment]
https://github.com/DeckerSU/KomodoOcean/commit/29575044675b2c1fd5d1309a4d55bbead8b8c494 - can we also add analog of this commit in current PR. This will prevent of spamming really big hex strings (in case of splitfund tx expired). I guess so detail log was needed for debug purposes, when we had transtition to overwinter / sapling. But now seems it's don't needed anymore.

**Comment by DeckerSU** [comment]
Seems i fixed it (need to test). There was a big difference, between how it was:
```
(ASSETCHAINS_SYMBOL[0] == 0
  && tipindex != 0 && komodo_validate_interest(...) ) < 0
```
and how it should be:
```
(ASSETCHAINS_SYMBOL[0] == 0
  && tipindex != 0 && komodo_validate_interest(...) < 0 )
```
More details here:
https://github.com/DeckerSU/KomodoOcean/commit/1fbf1c449ae321162e61f76fd7d5786e7383a682

**Pull request merged**
