### PR TITLE
Separate KOMODO_STATES and CURRENCIES

### PR DESCRIPTION
**Pull request by jmjatlanta**
Part of #479

The existing code looks up a pointer to `komodo_state` in an array, indexed by `CURRENCIES`.

This PR breaks that link, allowing the collection of komodo_state objects to
- Lazily grow - The komodo_state objects are created as needed
- Logarithmic lookups - the need to look up an index first is not necessary
- hold the symbol - Interrogate the object for the symbol instead of maintaining one locally

This PR also
- hide the `CURRENCIES` array behind a method. `komodo_currency(uint8_t) will return the currency symbol of a particular index.
- Breaks the two things that happened in `komodo_stateptr` (getting the symbol and the pointer) into two methods. This allows methods that do not need the `symbol` and `dest` values to not create variables for them.
- Override `komodo_stateptr` to give it the functionality of `komodo_stateptrget`. This provides a unified interface.

`komodo_stateptr()` now returns a pointer to komodo_state for the default chain.
`komodo_stateptr(char *)` now returns a pointer to komodo_state for the passed-in symbol.
`komodo_nameset(char*, char*, const char*)` can be used to set the `symbol` and `dest` as `komodo_stateptr` used to.

Note: It seems the `pax_` routines use the currency array quite a bit. I am unsure of the functionality of this code. This area should be tested heavily to assure no functionality is broken.

### CODE REVIEW

**Comment by dimxy** [comment]
I think these changes are great, however as they touch the notary code I'd suggest someone tries them on a NN node (@DeckerSU)

**Comment by dimxy** [comment]
probably this PR will need to be rebased after jmj_npoint is merged (f.e. it still uses sp->NUM_NPOINTS replace on NPOINTS.size())

**Review by dimxy — COMMENTED** [review]
Changes look great and there are tests for them but I still suggest a NN operator would try to use them and check for correct work (absence of errors in logs and console)

**Comment by jmjatlanta** [comment]
> currencies array:
> Is related to **PAX** "stable-coins" experiment.

If PAX code is indeed dead code, my vote would be to close or delay merging this PR, and scope-creep this into a "Remove PAX" PR.

**Comment by TheComputerGenie** [comment]
Given that we're giving up on LABS, shouldn't that come out too?

**Comment by jmjatlanta** [comment]
Closed in favor of #551

**Pull request closed without merging**
