### PR TITLE
Update TKL

### PR DESCRIPTION
**Pull request by smk762**
- added 'requestId' field into nSPV protocol v5 messages to provide multiple endpoints in the nSPV client app
- better error handling in nSPV protocol v5
- bitgo-kmd javascript library updated for nSPV protocol v5
- Build of customised tokeld, tokel-cli binaries (Tokel chain params are passed in configure)
- nspv maxrecords param added to listunspent, listtransactions
- missing cs_main locks fixed in nspv
- nspv rate limiter allows N req/sec
- new gettransactionsmany nspv method
- new C-prefix added for cc index keys (former 'cc addresses')
- added support for CLTV transactions to the daemon wallet and nSPV protocol
- remove unneeded build command and help message

### CODE REVIEW

**Comment by smk762** [comment]
@ca333 @NutellaLicka Once this is reviewed and merged, I'll initiate PR to dpow repo and start update process for NNs

**Comment by smk762** [comment]
@ca333 @dimxy ready for review :+1:

**Review by DeckerSU — APPROVED** [review]
LGTM, but it reviewed only for possible "malicious code" inclusions and explicit/obvious errors. Didn't deeply review against possible logic/algorithm issues in CC part or details of NSPV implementation.

- The idea of having special prefix (`CChainParams::CRYPTOCONDITION_ADDRESS`) for CC addresses
  looks nice and we might have such changes in Komodo codebase for future. Also i like the [idea](https://github.com/KomodoPlatform/komodo/pull/515/commits/f6c6808091ccc8da82d4105112de91e1a7223baa)
  of initialisation `unspendableCCaddr`, `normaladdr` without hardcoded addresses,
  using `_GetCCaddress` and `Getscriptaddress`. 
- The PR seems completely removed DNS seeds for TOKEL, probably good to setup at least
  one seeder using the variant of [komodo-seeder](https://github.com/DeckerSU/komodo-seeder) or one of the [dns seeder scripts (gandi, cloudflare)](https://github.com/DeckerSU/komodo_scripts/commit/3fce8434756cb9984603ba272eec86dce5750121). Also good to have TOKEL hardcoded seed nodes in `pnSeed6_main` of `chainparamsseeds.h`.
- About `cs_mapRelay` deadlock, may be we should follow Bitcoin upstream [#8126](https://github.com/bitcoin/bitcoin/pull/8126) and get rid of `cs_mapRelay` at all, protecting mapRelay by `cs_main` and [make it store CTransactions](https://github.com/bitcoin/bitcoin/commit/38c310299cfef419d42744362b90c1700b598953) instead of `CDataStream>`? I know such changes may be too complex, but anyway we might consider it for future.

**Comment by dimxy** [comment]
it is better not to have seeds in chainparamsseeds.h for assets chains as the default seeds point to KMD servers and just won't be used for assets chains (filling debug.log with connection errors). 
As whether a chain is 'assets' or not is defined at startup when the cmd line is parsed we could not have static seeds specific for an assets chain in the chainparamsseeds.h. So we need to use -addnode instead. 
Maybe to resolve this we could setup yet another CChainParams object for assets chains with empty seeds and have CMainParams only for main KMD chain (with its seeds)
(or any other ideas are welcomed)

**Comment by DeckerSU** [comment]
> it is better not to have seeds in chainparamsseeds.h for assets chains as the default seeds point to KMD servers and just won't be used for assets chains (filling debug.log with connection errors).

yes, you are right. but i guess here we are talking about customized binaries `tokeld`, `tokel-cli` etc. which probably will be used only with the `TOKEL` chain, so why to not add the fixed seeds? anyway, it's just a suggestion.

**Comment by dimxy** [comment]
yes with '#ifdef TOKEL' we could add some include file with their seeds, will add this

**Comment by NutellaLicka** [comment]
Thank you all!

**Pull request merged**
