### PR TITLE
[New ac_param] -ac_aur : Allow to enable active user reward on smartchains

### PR DESCRIPTION
**Pull request by phm87**
### **-ac_aur**

This pull request introduces a new Antara Customization parameter (ac_param) allowing to enable active user rewards on new smartchains using **-ac_aur**. Basic tests were performed manually successfully and a testchain (TAUR) is currently under test on #kmdlabs channel on Komodo discord, thank you to all KMDLabs notaries (and anonymous miners) that participates. Since TAUR network is not good (too few nodes), maybe a new testchain will be launched.
https://gist.github.com/phm87/fc75d5820d232376a8256874726673b4
https://discord.com/channels/412898016371015680/497080413387489291/780873228838895626

Please do not merge yet, I still need to do some cleanup (see below) and more tests performed.

**-ac_aur** needs several parameters separated by commas: Enable/disable active user rewards (parameters: 1, activationHeight (60000), minCoins (10), LOCKTIME_THRESHOLD (500000000), percentage (5)), default is disable
Example (TAUR): -ac_aur=1,10,2,500000000,10 will enable active user rewards activated at block 10, min 2 coins to earn AUR, min locktime identical to Komodo (500000000), Percentage per year of 10%

TAUR_help

TAUR_getinfo

As discussed with @PTYX on discord, allowing to enable AUR on smartchains can be a good idea.

**What was done in the code ?**
- src/coins.cpp src/komodo_bitcoind.h src/komodo_gateway.h src/komodo_interest.h src/main.cpp src/miner.cpp src/rpc/misc.cpp src/wallet/rpcwallet.cpp src/wallet/wallet.cpp : code changes related to enabling active user rewards for smartchains and not restrict it to Komodo only)
- src/init.cpp strUsage documentation how to use -ac_aur
- src/komodo_defs.h src/komodo_globals.h : internal definitions of -ac_aur data as ASSETCHAINS_ACTIVEUSERREWARD
- src/komodo_utils.h : the sub-parameters used in _ac_aur=sub-parameters separated by commas are splitted into ASSETCHAINS_ACTIVEUSERREWARD data structure & some checks are performed on allowed values & adapt extraptr and extralen if -ac_aur is used (
- src/notaries_staked.cpp : change that I need to clean before PR is merged

**A part of To do's:**
- I tried to execute python regression tests (where TONYCL chain is synced) but I encountered problems, unsure if it is due to test configuration or to python installation. I'll ask some help to @tonymorony about how to run usual python regression tests to be sure that there is no regression when -ac_aur is not used.
- I tested manually each forbidden value in the sub-parameters of -ac_aur= (i.e. negative percentage per year is forbidden in this implementation) but is it worth to be automated ?
- Another idea to be discussed with @Alright would be to automate for parameters identical to Komodo and compare with a Komodo node
- Maybe I should open another PR to update the docs:
https://developers.komodoplatform.com/basic-docs/antara/antara-setup/antara-customizations.html
- I left on purpose few interrogation marks on purpose in my code changes, I don't think that I need to change these lines but it is worth to be discussed

Thank you to Alright, KMDLabs team, KMD Team, jl777 and PTYX.

### CODE REVIEW

**Comment by ca333** [comment]
outdated/conflicts

**Comment by rusaik** [comment]
Is this parameter available to use in smart chain ? I would like this parameter to implemented in the smart chain i have created.

**Comment by dimxy** [comment]
> Is this parameter available to use in smart chain ? I would like this parameter to implemented in the smart chain i have created.

There is no such ac_aur parameter supported in the official repo

**Comment by rusaik** [comment]
I would like to make request to make this feature available on Smart Chains, Could you please help me on this ?

**Comment by dimxy** [comment]
> I would like to make request to make this feature available on Smart Chains, Could you please help me on this ?

I am afraid we do not have plans to add such a param in the nearest future.
If you'd like to start your own chain with this param activated I'd suggest you may make a repo fork and add this code there

**Pull request closed without merging**
