### PR TITLE
Update depends

### PR DESCRIPTION
**Pull request by TheComputerGenie**
new config.sub
new config.guess
set vars before trying to use them

closes #633, #634, and #635

### CODE REVIEW

**Comment by TheComputerGenie** [comment]
For clarity, this is a newer patch than #634 and the fix for depends/funcs.mk fixes the issue in #633 and removes any need for #635 since the vars are set before they are needed and no need to move them to a place they don't "belong" just to get them to exist.

**Comment by DeckerSU** [comment]
What's the purpose of updating `config.sub` / `config.guess` right now if we're only supporting the `x86_64-unknown-linux-gnu`, `x86_64-w64-mingw32`, and `x86_64-apple-darwin` triplets, which are already being detected correctly? We could use the latest [config.guess](https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD) from git.savannah.gnu.org, but as I recall, it could introduce some issues. For instance, the canonical system name for Linux might change from `x86_64-unknown-linux-gnu` to `x86_64-pc-linux-gnu`, which would lead to unexpected behavior in some places, such as the Rust dependencies installation (which would also need to be updated). 

Of course, we could update the entire build system to align with the new `config.sub`, but what's the real benefit of doing this right now? Is it just for the sake of "at least being in the same decade as the OSs we're guessing at," as you mentioned [here](https://github.com/KomodoPlatform/komodo/pull/634)?

**Comment by DeckerSU** [comment]
> it should be updated when there are systems that it doesn't work

On which systems exactly, that we support, does the current code not work? Can you provide some examples?

Anyway, thank you so much for your contribution and for taking the time to propose an update for `config.guess` and `config.sub` to support new OS detection. We really appreciate your effort and attention to detail in helping improve the project.

At the moment, seems the current versions of these scripts already cover all the systems we officially support. As a result, we won’t be updating them right now. However, we’ll definitely consider your changes when we revisit this in the future.

Please don’t hesitate to contribute again in the future. Your efforts are always welcome!

**Comment by TheComputerGenie** [comment]
> On which systems exactly, that we support, does the current code not work? Can you provide some examples?

You already did that, and it's sad that I have to point that out.

> the canonical system name for Linux might change from `x86_64-unknown-linux-gnu` to `x86_64-pc-linux-gnu`

That it "technically" "works" shouldn't be the standard. That it works **properly** and **properly identifies** as many setups as possible _should be_ the standard!

**Comment by DeckerSU** [comment]
Thank you for PR #636! We’re closing it in favor of PR #641, which builds on your ideas. Your contribution is much appreciated! 🙏

**Pull request closed without merging**
