### PR TITLE
[QA] Pytest-based RPC and CC tests updates

### PR DESCRIPTION
**Pull request by SirSevenG**

### CODE REVIEW

**Comment by tonymorony** [comment]
Tests not passed @SirSevenG

**Comment by SirSevenG** [comment]
Updated bootstrap to have more UTXOs for test addresses, issue was bootstrap related.

**Comment by leto** [comment]
@SirSevenG @tonymorony KMD test suite has come a long way, nice work :+1:

**Comment by tonymorony** [comment]
Thank you @leto !

**Pull request merged**
