### PR TITLE
use py3, ubuntu 20, allow brew update errors to continue

### PR DESCRIPTION
**Pull request by smk762**
@SirSevenG there are some failing tests on CCs and with windows, can you please have a look?

### CODE REVIEW

**Comment by dimxy** [comment]
We have a long term problem with the building the tests on MacOS and Windows (this is apparently due to some CI environment that has changed), but Linux tests normally build and work pretty well. Now even LInux build failed. Maybe it is a one-time error and re-run would help?

**Comment by smk762** [comment]
some of the changes only trigger on push to dev / beta / research branches https://github.com/KomodoPlatform/komodo/blob/dev/.github/workflows/komodod_cd.yml

I did some prior testing on https://github.com/smk762/komodo/actions for this, mostly to get the dockerhub image side of things working on ubuntu 20 (https://hub.docker.com/repository/docker/smk762/komodo/general) as I was trying to use the image in another repo but it was failing due to old python version in 18.04 base image.

**Comment by dimxy** [comment]
I restarted Linux and MacOs tests, expecting Linux should pass and for MacOs it usually failed on a different error than it occurs now

**Comment by smk762** [comment]
> failed on a different error 
Hopefully one after the old one and not before :sweat_smile:
QA have a closer look at this next week to try and resolve in line with HF updates.

**Review by DeckerSU — APPROVED** [review]
LGTM, in terms of changing `python -> python3` and Ubuntu `18 -> 20`.

**Comment by SirSevenG** [comment]
Workflow changes looks fine.
Windows CI fail here looks to be due GH Actions connection issue, yet there are a few possible issue with test.
Will check it when have time.

**Comment by SirSevenG** [comment]
Looks like more fresh and stable version of cc_modules tests are still in research branch.
Will need to sync qa/pytest_komodo directories between research and dev.

**Review by SirSevenG — APPROVED** [review]
Will open separate PR for tests and WIndows CI fixes.

**Pull request merged**
