### PR TITLE
[WIP] TransactionPool

### PR DESCRIPTION
**Pull request by jmjatlanta**
The code to handle the Mempool is complicated when an incoming block is connected to the chain. The hope is to have the code into a "Mempool-like" class that centralizes and hides this complexity.

**Note:** This was branched from jmj_testutils to make debugging easier. You may wish to review and merge that branch first.

### CODE REVIEW

**Comment by dimxy** [comment]
Regarding this commit https://github.com/KomodoPlatform/komodo/pull/521/commits/9e63d65123254d3b93204919f162ac3da156d619
here is my concerns:
As I understand it, removeForReorg() removes transactions that have become non-final or immature (if spend coinbases). it is called after some blocks have been disconnected in ActivateBestChainStep() - as if those transactions would not be added to the mempool if the tip height was like it is now, after disconnecting blocks.
This commit assumes that if a new fork activation has failed we already do not need to call removeForReorg. However it seems blocks are disconnected anyway even the fork activation has failed; so at this moment transactions may exist that are now immature or non-final and need to be removed, I think.

**Comment by jmjatlanta** [comment]
You are probably correct. I will research. Thanks for the review.

**Comment by jmjatlanta** [comment]
One of the things I am struggling with is coming up with edge cases that involve:
1. A transaction in the mempool that will affect (good or bad) a CC, whereby that same transaction is not part of the block. Is there such a case? If so, I would like to write a test for it.
2. If a transaction is in the mempool, and then the chain forks "A" and "B", and a block on the B fork uses the mempool transaction then that fork fails to be the longest chain, what should happen to the mempool? Currently, the transaction has been removed from the mempool.

**Comment by dimxy** [comment]
I think we should not remove anything from the main mempool.
We need to create a dedicated transaction pool and make it available for the cc validation code when it is called while blocks are connected.
actually cc validation code starts from here: https://github.com/KomodoPlatform/komodo/blob/db4044037df455544cd325bb8b4cbaa7ecc0a383/src/main.cpp#L3697 (check objects are created here and sent to a queue to be processed in another thread)
 so maybe we could move the tx pool creation here and make it available for cc validation code in the eval object

**Comment by jmjatlanta** [comment]
To provide CCs with an appropriate CTxMemPool to evaluate during block processing, I am thinking of adding a block-derived CTxMemPool to the Eval class, and requiring that it be passed to the Eval constructor.

Currently the Eval object used to evaluate CCs is a singleton. It seems it has no data members, so I am not sure why it is a singleton. In its current state it is trivially constructable so performance is probably not a consideration.

My idea is to construct an Eval for each block, passing the CTxMemPool that only contains the block's transactions, which later gets passed to myGetTransaction. This will allow the process to use the appropriate "mempool" to use with CC evaluation without a lot of changes.

2 Questions:
1. Is there a problem switching Eval from a singleton to a typical object? (what am I missing?)
2. Any holes in my idea of giving Eval a member that is the mempool we want to look through?

**Comment by jmjatlanta** [comment]
A partial answer for question #1... EvalRef is used in a few places within the CCs. So to move from a singleton the Eval object would need to be passed down to certain CC methods. I don't see that as a big obstacle however.

**Comment by dimxy** [comment]
I think adding a tx pool object to the eval is great. That's what I would do
This EvalRef global object is for cc tests I believe. I use such tests (in tokel branches) so I could check if you suggest how to change it (and having the tx pool object in the eval would allow for cc tests to work too)

**Comment by dimxy** [comment]
it looks like this will work.
So you need yet to make GetTxUnconfirmed work with the eval.pool.
Wondering why the oracles test failed, the log was showing it could crash

**Pull request closed without merging**
