### PR TITLE
sync master

### PR DESCRIPTION
**Pull request by ca333**
mandatory update

### CODE REVIEW

**Comment by ca333** [comment]
@tonymorony @himu007 - plz ACK

**Comment by tonymorony** [comment]
ACK @ca333

**Comment by himu007** [comment]
Is this sync for latest release and hardupdate?
jl777's master branch is 23 days behind and doesn't have season 3 NN keys.

**Comment by himu007** [comment]
in general this branch is ok and compiles. also starts coin. so...

ACK @ca333 

but for hardfork update of NN season 3, not ready.

**Pull request merged**
