### PR TITLE
Combined PR for jmj refactoring

### PR DESCRIPTION
**Pull request by dimxy**
This is a combined PR for #452 #453 #463 #485 #486 #490 #505 #506 #507 #508 #509 #510 #512 #514 #516 #520 #548 #551 #552 #556

Closes https://github.com/KomodoPlatform/komodo/issues/555 https://github.com/KomodoPlatform/komodo/issues/554 #483 #480 #478

### CODE REVIEW

**Review by DeckerSU — APPROVED** [review]
LGMT. I guess we should test it once again, but now with `#nn-quarantine` group. If everything is Ok - i guess we could merge it.

**Review by TheComputerGenie — COMMENTED** [review]
The daemon doesn't have _uiInterface_.

**Review by DeckerSU — CHANGES_REQUESTED** [review]
Too early. Found one mistake, will push the fix soon.

**Review by DeckerSU — APPROVED** [review]
LGTM for `dev` branch.

**Review by ca333 — APPROVED** [review]

**Pull request merged**
