### PR TITLE
[release] v0.8.1 [Falkor]

### PR DESCRIPTION
**Pull request by ca333**

### CODE REVIEW

**Comment by smk762** [comment]
The Actions workflows output for linux fail to launch in Ubuntu 20.04
```
./komodod: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by ./komodod)
./komodod: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./komodod)
./komodod: /lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by ./komodod)
./komodod: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./komodod)
./komodod: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./komodod)
./komodod: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./komodod)
```

**Comment by DeckerSU** [comment]
> The Actions workflows output for linux fail to launch in Ubuntu 20.04

I believe that the `komodo_linux_ci.yml` workflow is failing because it's running on `ubuntu-latest`, which is currently `ubuntu-22.04`. The `komodod_cd.yml` workflow, however, is using `ubuntu-20.04`. To resolve this issue, we should either use Ubuntu 20.04 in both workflows or build for multiple GLIBC versions, as I have done in the KomodoOcean repository. The KomodoOcean builds successfully with Xenial (and works on Xenial and later releases) as well as Focal. The release binaries include both builds.

**Comment by DeckerSU** [comment]
It's because `komodod` file content is not even `Mach-O 64-bit executable x86_64`:

image

I remember such issue exists bcz of incompatibility or rust + XCode version. Switching to `macos-11` should help.

**Review by Alrighttt — APPROVED** [review]

**Comment by ca333** [comment]
> maybe we need to use `macos-11` for builds instead of `macos-latest`. I'll test this and PR CI/CD updates accordingly.
> 

yes best is to build with "older" (sec patched / supported) version for wider (backwards) compatibility

**Comment by DeckerSU** [comment]
> maybe we need to use `macos-11` for builds instead of `macos-latest`. I'll test this and PR CI/CD updates accordingly.

Issue resolved. The [root](https://github.com/KomodoPlatform/komodo/pull/618#issuecomment-1987320216 ) cause was identified as `bsdtar` on MacOS, which was causing file corruption during archive creation.

**Pull request merged**
