### PR TITLE
Implement TLS support for encrypted p2p communication

### PR DESCRIPTION
**Pull request by CryptoForge**

### CODE REVIEW

**Review by jmjatlanta — CHANGES_REQUESTED** [review]
Minor suggestions, should it be decided to merge this, tests should be written to verify functionality and compatibility.

**Comment by dimxy** [comment]
should this first be merged into dev branch?

**Comment by jmjatlanta** [comment]
These changes are somewhat segregated, and the code is not changed often. So in my opinion, they could be merged whenever and wherever it makes sense.

**Comment by DeckerSU** [comment]
I guess we should follow Bitcoin upstream, and what about p2p encryption - they have [BIP: 324 - Version 2 Peer-to-Peer Message Transport Protocol](https://gist.github.com/jonasschnelli/c530ea8421b8d0e80c51486325587c52#v2_Messages_Structure). From my point of view this [implementation](https://github.com/bitcoin/bitcoin/pull/14032) is preferable, and we might want to merge these changes in our repo, once Bitcoin will accept it. 

I see no reason in merge ZEN implementation of tls encryption based on OpenSSL right now (if i don't wrong, this PR originally derived from Horizen), but of course it's open discussion and if you have other opinion and strong arguments why we need exactly this - it's very interesting to hear them.

**Comment by CryptoForge** [comment]
Due to the DMCA issued against Pirate, do not merge this pull request.

**Pull request closed without merging**
