### PR TITLE
Correctly serialize komodostate records

### PR DESCRIPTION
**Pull request by jmjatlanta**
When writing to the `komodostate` file, the object memory address was inserted into the stream instead of the actual object, thereby corrupting the file. This fix correctly serializes the object.

### CODE REVIEW

**Comment by jmjatlanta** [comment]
Following the suggestion of @dimxy I refactored to remove dynamic casts.

**Review by dimxy — APPROVED** [review]
looks good to me.
I hope tests are enough to cover usage cases

**Comment by jmjatlanta** [comment]
> looks good to me. I hope tests are enough to cover usage cases

Good point. Currently only 1 object is being serialized and tested. I will test the others.

**Comment by DeckerSU** [comment]
Unfortunately (my bad also, bcz besides of many tests I missed it) with events sources update we are completely break `komodostate` file filling. The root of the issue is really in:
```
size_t write_event(std::shared_ptr<komodo::event> evt, FILE *fp)
{
    std::stringstream ss;
    ss << evt;
    std::string buf = ss.str();
    return fwrite(buf.c_str(), buf.size(), 1, fp);
}
```
Which writes a pointer of event in ASCII, like `0x7f8c3831c420` to `komodostate` file, instead of a real event object serialisation. Probably I missed it bcz somehow thought/imagine that `<<` operator in it uses standart Bitcoin serialisation from `serialize.h` (I mean `Serialize`/`Unserialize` methods which are perfectly working with `shared_ptr`, `unique_ptr`, etc.), but it's not true and `<<` operator here is actually from STL (`shared_ptr.h`).

This commit seems fix this behaviour, but `komodostate` file after applying #548 changes anyway creating with errors in serialisation. I had small tests in this repo - [events-refactor-test
](https://github.com/DeckerSU/events-refactor-test) to parse `komodostate` file using old code (before we applied events sources changes) and new code (after). Also repo have two example `komodostate` files (`komodostate` and `komodostate.pirate`) which should be identically parsed by old and new code. Example:

```
read_count = 741255
rewind_count = 1969
sp->NUM_NPOINTS = 56774
sp->Komodo_numevents = 736922

read_count = 741255
rewind_count = 1969
sp->NUM_NPOINTS = 56774
sp->events.size() = 736922
```

But ... `komodostate` file produced by `komodod` from `dev` branch with #548 applied produced bad `komodostate` file, which can't be parsed neither old nor new code. I mean if we'll repeat the following steps:

1. Build latest `dev` branch komodod with #548 applied.
2. Delete `komodostate` file from data directory.
3. Launch daemon on KMD or on AC for a few minutes to get `komodostate` file filled with data.
4. Stop the daemon.
5. Test result `komodostate` file with `events-test`.

We will find out that file produced by `dev` + #548 `komodod` is broken and can't be parsed. So, to approve this PR we should solve this issue first. Daemon should produce correct state file which should be 100% parsed by OLD and NEW events code.

**Comment by DeckerSU** [comment]
Found one root of issue (may be there are more). It's incorrect `komodo::event_notarized` serialization in case of negative `MoMdepth`. New events code (after refactoring) in case of MoMdepth < 0 uses `M` prefix for event serialization, but doesn't append `MoM` and `MoMdepth` to `komodostate` file. And when we parsing `komodostate` file and meet the `M` event, we anyway trying to read `MoM` and `MoMdepth` it from file. As a result data of other event is counted as `MoM` and `MoMdepth` of `EVENT_NOTARIZED` and file become corrupted from an app point of view.

Small example, here is the serialization of written to file:
```
4d3ad901002ad90100fb48335c1efd838a27471ea8ae5039c4fddd16595d890830581167c8001800002d6e68d7d12ccac21ea945cfa455d83fecc274e9ee29d024f776774cc30234b4
```
Let's see what's this:
```
        4d (M) - func
        3ad90100 (121146) - ht
        2ad90100 (121130) - notarized_height
        fb48335c1efd838a27471ea8ae5039c4fddd16595d890830581167c800180000 - notarized_hash
        2d6e68d7d12ccac21ea945cfa455d83fecc274e9ee29d024f776774cc30234b4 - notarized_desttxid
        ? = MoM (uint256)
        ? = MoMdepth (int32_t)
```
As we are see it's started from `0x4d (M)`, but the required (`MoM`, `MoMdepth`) fields are absent.

**Comment by dimxy** [comment]
write_event was not used in tests in the current dev branch (a custom function for writing was used instead) so tests did not show this bug. (This PR already adds write_event into the tests)
I traced komodostate_parsefiledata and it prints garbage instead of normal funcids from a certain moment. 
Maybe we could add a new komodod option to rebuild komodostate only.

**Comment by DeckerSU** [comment]
Almost fixed, I'll keep you updated.

**Comment by DeckerSU** [comment]
So ... I carefully tested everything ... latest `dev` branch komodod with #548 applied and with [my fix](https://github.com/jmjatlanta/komodo/pull/26) for event_notarized with negative MoMdepth (if you will refer to old events code you will understand the meaning of this fix, or just need explore the [test](https://github.com/DeckerSU/events-refactor-test/commit/96d5a1d205bb8d4a650a41f251daa08f3e646af7#diff-bef50f3d9bda95f4f54684b9313f7db5ec069730c72194e102df3288539dcfa4R1801-R1818):

This event:
```cpp
uint8_t notarized_hash_u8[] = { 0xfb,0x48,0x33,0x5c,0x1e,0xfd,0x83,0x8a,0x27,0x47,0x1e,0xa8,0xae,0x50,0x39,0xc4,0xfd,0xdd,0x16,0x59,0x5d,0x89,0x08,0x30,0x58,0x11,0x67,0xc8,0x00,0x18,0x00,0x00 };
uint8_t desttxid_u8[]       = { 0x2d,0x6e,0x68,0xd7,0xd1,0x2c,0xca,0xc2,0x1e,0xa9,0x45,0xcf,0xa4,0x55,0xd8,0x3f,0xec,0xc2,0x74,0xe9,0xee,0x29,0xd0,0x24,0xf7,0x76,0x77,0x4c,0xc3,0x02,0x34,0xb4 };
uint8_t MoM_u8[]            = { 0x41,0x74,0x9e,0x72,0x8b,0x6d,0x56,0x8e,0x6f,0x52,0x23,0x4a,0xcb,0xb5,0xe6,0x36,0xd2,0x88,0xbf,0x1a,0x27,0x8f,0x65,0x4c,0x25,0x07,0xac,0x2e,0x81,0x74,0x15,0xc1 };

/* EVENT_NOTARIZED with negative MoMdepth */
komodo::event_notarized evt_notarized(121146 /*ht*/, "KMD");
ser.clear();
evt_notarized.notarizedheight = 121130;
std::copy(notarized_hash_u8, notarized_hash_u8 + 32, evt_notarized.blockhash.bytes);
std::copy(desttxid_u8, desttxid_u8 + 32, evt_notarized.desttxid.bytes);
std::copy(MoM_u8, MoM_u8 + 32, evt_notarized.MoM.bytes);
evt_notarized.MoMdepth = 0xf80002b3; /* negative */

ser = HexStr((std::stringstream() << evt_notarized).str());
std::cout << "EVENT_NOTARIZED: " << ser << std::endl;
write_event(evt_notarized, fp);
```
Should be serialized like:
```
4d3ad901002ad90100fb48335c1efd838a27471ea8ae5039c4fddd16595d890830581167c8001800002d6e68d7d12ccac21ea945cfa455d83fecc274e9ee29d024f776774cc30234b441749e728b6d568e6f52234acbb5e636d288bf1a278f654c2507ac2e817415c1b30200f8
```
But due to a bug in serialization code `MoM` and `MoMdepth` fields are not serialized, and with #548 only it serialized like:
```
4d3ad901002ad90100fb48335c1efd838a27471ea8ae5039c4fddd16595d890830581167c8001800002d6e68d7d12ccac21ea945cfa455d83fecc274e9ee29d024f776774cc30234b4
```
Which is cause komodostate file corruption, bcz next event will read not like a new event, but as a part of current event notarized, mean, header of the next event is read as `MoM` and `MoMdepth`. That's why komodod can't parse komodostate correctly.

With applied #548 and applied [fix](https://github.com/jmjatlanta/komodo/pull/26) error is fixed and komodod produce well parseable [komodostate](https://download.kmd.sh/komodo/komodostate.zip) file (you can download it for tests). Also produced file passed all tests with [events-refactor-test](https://github.com/DeckerSU/events-refactor-test) tool. Old and new code perfectly reads all events from it:
```
read_count = 3304788
rewind_count = 3778
sp->NUM_NPOINTS = 221195
sp->Komodo_numevents = 3272485

read_count = 3304788
rewind_count = 3778
sp->NUM_NPOINTS = 221195
sp->events.size() = 3272485
06346d285d489234435fa3f28c90f037028a88f57581a8fe7d37761c97cea410
```

So the next our steps, as I imagine them:
1. We should merge [fix](https://github.com/jmjatlanta/komodo/pull/26) in `jmjatlanta:jmj_event_fix3` branch.
2. Test the #548 once again with applied fix (did a full sync with `dev` + `#548` and fix from (1))
3. If everything is Ok - merge (2).

**Comment by tonymorony** [comment]
these changes implemented in combined PR: https://github.com/KomodoPlatform/komodo/pull/559

**Pull request closed without merging**
