### PR TITLE
Ci tests update

### PR DESCRIPTION
**Pull request by smk762**

### CODE REVIEW

**Comment by DeckerSU** [comment]
As i see build failed with:
```
2023-03-17T11:43:10.8200340Z /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:190:6: note: declared here
2023-03-17T11:43:10.8200720Z  int  sprintf(char * __restrict, const char * __restrict, ...) __printflike(2, 3);
2023-03-17T11:43:10.8200990Z       ^~~~~~~
2023-03-17T11:43:10.8201210Z In file included from main.cpp:7111:
2023-03-17T11:43:10.8202370Z komodo_nSPV_wallet.h:420:57: error: 'int sprintf(char*, const char*, ...)' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror=deprecated-declarations]
2023-03-17T11:43:10.8203190Z              sprintf(numstr,"%.8f",(double)rewardsum/COIN);
```
A temp solution could be add `-Wno-deprecated-declarations` in CXXFLAGS, like this:
```diff
diff --git a/zcutil/build-mac-dtest.sh b/zcutil/build-mac-dtest.sh
index 8104c7200..04c1d8ad8 100755
--- a/zcutil/build-mac-dtest.sh
+++ b/zcutil/build-mac-dtest.sh
@@ -52,7 +52,7 @@ cd $WD
 
 ./autogen.sh
 CPPFLAGS="-I$PREFIX/include -arch x86_64 -DTESTMODE" LDFLAGS="-L$PREFIX/lib -arch x86_64 -Wl,-no_pie" \
-CXXFLAGS='-arch x86_64 -I/usr/local/Cellar/gcc\@8/8.3.0/include/c++/8.3.0/ -I$PREFIX/include -fwrapv -fno-strict-aliasing -Wno-builtin-declaration-mismatch -Werror -Wno-error=attributes -g -Wl,-undefined -Wl,dynamic_lookup' \
+CXXFLAGS='-arch x86_64 -I/usr/local/Cellar/gcc\@8/8.3.0/include/c++/8.3.0/ -I$PREFIX/include -fwrapv -fno-strict-aliasing -Wno-builtin-declaration-mismatch -Wno-deprecated-declarations -Werror -Wno-error=attributes -g -Wl,-undefined -Wl,dynamic_lookup' \
 ./configure --prefix="${PREFIX}" --with-gui=no "$HARDENING_ARG" "$LCOV_ARG"
 
 make "$@" V=1 NO_GTEST=1 STATIC=1
```

**Comment by dimxy** [comment]
fixes #560 in Macos part

**Comment by DeckerSU** [comment]
> I re-ran Macos tests here and they again failed with `OSError: [Errno 8] Exec format error: '../../src/komodod'` Maybe when we apply Decker's #577 which switches to gcc-12 this error will be fixed

Exactly ... the `gcc-8` seems producing incorrect binaries on MacOS 12 / latest XCode ... Have no idea why, didn't investigate this case, but with `gcc-12` - seems everything is Ok.

**Comment by ca333** [comment]
archive

**Pull request closed without merging**
