### PR TITLE
updates the assetchains.old file to add "$1" at the end of all the ch…

### PR DESCRIPTION
**Pull request by gcharang**
…ain parameters

### CODE REVIEW

**Comment by gcharang** [comment]
@ca333 @tonymorony please review

**Comment by tonymorony** [comment]
Isn't $1 adding seednode ip as addnode?

**Comment by gcharang** [comment]
we can add or remove them. I just wanted to make them consistent for all chains. I guess it can be used to launch all the chains with `-reindex` or `-rescan`

**Comment by TheComputerGenie** [comment]
>...I just wanted to make them consistent for all chains...

You mean like this:
https://github.com/KomodoPlatform/komodo/pull/373#issuecomment-651069364
?

**Comment by gcharang** [comment]
> You mean like this

yes, just like that. Full explanation
```
didn't think the comment was directed at me. I checked the git blame later and it looks like it was my commit that removed those $1 s. it was because I didn't notice the difference when I hastily copy pasted the file from the dpow repo to here
```
sent a PR to the dPoW repo as well to fix it: https://github.com/KomodoPlatform/dPoW/pull/180

**Pull request merged**
